import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import openapiTS, { astToString } from 'openapi-typescript';

const contractDirectory = fileURLToPath(new URL('../', import.meta.url));
const schemaURL = new URL('../openapi.yaml', import.meta.url);
const outputs = [
  new URL('../../web/src/http/generated/openapi.ts', import.meta.url),
  new URL('../../admin/src/http/generated/openapi.ts', import.meta.url),
];
const checkOnly = process.argv.includes('--check');
const header = [
  '// Generated from contracts/openapi.yaml by cd contracts && corepack pnpm generate.',
  '// Do not edit this file directly.',
  '',
].join('\n');

const ast = await openapiTS(schemaURL, { alphabetize: true });
const generated = `${header}${astToString(ast)}`;
const stale = [];

for (const outputURL of outputs) {
  const outputPath = fileURLToPath(outputURL);
  if (checkOnly) {
    let current = '';
    try {
      current = await readFile(outputPath, 'utf8');
    } catch (error) {
      if (error?.code !== 'ENOENT') throw error;
    }
    if (current !== generated) stale.push(outputPath);
    continue;
  }
  await mkdir(fileURLToPath(new URL('./', outputURL)), { recursive: true });
  await writeFile(outputPath, generated, 'utf8');
}

if (stale.length > 0) {
  const relative = stale.map(path => path.replace(`${contractDirectory}/../`, '')).join(', ');
  throw new Error(
    `Generated OpenAPI types are stale: ${relative}. Run cd contracts && corepack pnpm generate.`,
  );
}
