version: 2

updates:
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
      time: "05:10"
      timezone: Europe/Dublin
    open-pull-requests-limit: 5
    groups:
      web-production-minor-patch:
        dependency-type: production
        update-types: [minor, patch]
      web-development-minor-patch:
        dependency-type: development
        update-types: [minor, patch]
    commit-message:
      prefix: deps(web)

  - package-ecosystem: gomod
    directory: /api
    schedule:
      interval: weekly
      day: monday
      time: "05:20"
      timezone: Europe/Dublin
    open-pull-requests-limit: 5
    groups:
      go-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]
    commit-message:
      prefix: deps(api)

  - package-ecosystem: npm
    directory: /web-spa
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: Europe/Dublin
    open-pull-requests-limit: 5
    groups:
      web-spa-production-minor-patch:
        dependency-type: production
        update-types: [minor, patch]
      web-spa-development-minor-patch:
        dependency-type: development
        update-types: [minor, patch]
    commit-message:
      prefix: deps(web-spa)

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Dublin
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns: ["*"]
        update-types: [minor, patch]
    commit-message:
      prefix: deps(actions)

  - package-ecosystem: docker
    directory: /api
    schedule:
      interval: weekly
      day: monday
      time: "05:40"
      timezone: Europe/Dublin
    open-pull-requests-limit: 3
    groups:
      api-images:
        patterns: ["*"]
        update-types: [minor, patch]
    commit-message:
      prefix: deps(api-image)

  - package-ecosystem: docker
    directory: /web
    schedule:
      interval: weekly
      day: monday
      time: "05:50"
      timezone: Europe/Dublin
    open-pull-requests-limit: 3
    groups:
      web-images:
        patterns: ["*"]
        update-types: [minor, patch]
    commit-message:
      prefix: deps(web-image)
