/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as ConsolePreferencesRouteImport } from './routes/console.preferences'
import { Route as ConsoleUsersRouteImport } from './routes/console.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsolePreferencesRoute = ConsolePreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleUsersRoute = ConsoleUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/console/preferences': typeof ConsolePreferencesRoute
  '/console/users': typeof ConsoleUsersRoute
  '/console/': typeof ConsoleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/console/preferences': typeof ConsolePreferencesRoute
  '/console/users': typeof ConsoleUsersRoute
  '/console': typeof ConsoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/console/preferences': typeof ConsolePreferencesRoute
  '/console/users': typeof ConsoleUsersRoute
  '/console/': typeof ConsoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/login'
    | '/console/preferences'
    | '/console/users'
    | '/console/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/console/preferences' | '/console/users' | '/console'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/login'
    | '/console/preferences'
    | '/console/users'
    | '/console/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/preferences': {
      id: '/console/preferences'
      path: '/preferences'
      fullPath: '/console/preferences'
      preLoaderRoute: typeof ConsolePreferencesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/users': {
      id: '/console/users'
      path: '/users'
      fullPath: '/console/users'
      preLoaderRoute: typeof ConsoleUsersRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsolePreferencesRoute: typeof ConsolePreferencesRoute
  ConsoleUsersRoute: typeof ConsoleUsersRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsolePreferencesRoute: ConsolePreferencesRoute,
  ConsoleUsersRoute: ConsoleUsersRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
