/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as ConsoleAuditRouteImport } from './routes/console.audit'
import { Route as ConsoleNotificationsRouteImport } from './routes/console.notifications'
import { Route as ConsolePreferencesRouteImport } from './routes/console.preferences'
import { Route as ConsoleSettingsRouteImport } from './routes/console.settings'
import { Route as ConsoleUsersRouteImport } from './routes/console.users'
import { Route as ConsoleOrganizationsIndexRouteImport } from './routes/console.organizations.index'
import { Route as ConsoleOrganizationsOrganizationIdRouteImport } from './routes/console.organizations.$organizationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAuditRoute = ConsoleAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleNotificationsRoute = ConsoleNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsolePreferencesRoute = ConsolePreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleUsersRoute = ConsoleUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOrganizationsIndexRoute =
  ConsoleOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleOrganizationsOrganizationIdRoute =
  ConsoleOrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => ConsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/notifications': typeof ConsoleNotificationsRoute
  '/console/preferences': typeof ConsolePreferencesRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/users': typeof ConsoleUsersRoute
  '/console/': typeof ConsoleIndexRoute
  '/console/organizations/$organizationId': typeof ConsoleOrganizationsOrganizationIdRoute
  '/console/organizations/': typeof ConsoleOrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/notifications': typeof ConsoleNotificationsRoute
  '/console/preferences': typeof ConsolePreferencesRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/users': typeof ConsoleUsersRoute
  '/console': typeof ConsoleIndexRoute
  '/console/organizations/$organizationId': typeof ConsoleOrganizationsOrganizationIdRoute
  '/console/organizations': typeof ConsoleOrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/notifications': typeof ConsoleNotificationsRoute
  '/console/preferences': typeof ConsolePreferencesRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/users': typeof ConsoleUsersRoute
  '/console/': typeof ConsoleIndexRoute
  '/console/organizations/$organizationId': typeof ConsoleOrganizationsOrganizationIdRoute
  '/console/organizations/': typeof ConsoleOrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/login'
    | '/console/audit'
    | '/console/notifications'
    | '/console/preferences'
    | '/console/settings'
    | '/console/users'
    | '/console/'
    | '/console/organizations/$organizationId'
    | '/console/organizations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/console/audit'
    | '/console/notifications'
    | '/console/preferences'
    | '/console/settings'
    | '/console/users'
    | '/console'
    | '/console/organizations/$organizationId'
    | '/console/organizations'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/login'
    | '/console/audit'
    | '/console/notifications'
    | '/console/preferences'
    | '/console/settings'
    | '/console/users'
    | '/console/'
    | '/console/organizations/$organizationId'
    | '/console/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/audit': {
      id: '/console/audit'
      path: '/audit'
      fullPath: '/console/audit'
      preLoaderRoute: typeof ConsoleAuditRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/notifications': {
      id: '/console/notifications'
      path: '/notifications'
      fullPath: '/console/notifications'
      preLoaderRoute: typeof ConsoleNotificationsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/preferences': {
      id: '/console/preferences'
      path: '/preferences'
      fullPath: '/console/preferences'
      preLoaderRoute: typeof ConsolePreferencesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings': {
      id: '/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/users': {
      id: '/console/users'
      path: '/users'
      fullPath: '/console/users'
      preLoaderRoute: typeof ConsoleUsersRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/organizations/': {
      id: '/console/organizations/'
      path: '/organizations'
      fullPath: '/console/organizations/'
      preLoaderRoute: typeof ConsoleOrganizationsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/organizations/$organizationId': {
      id: '/console/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/console/organizations/$organizationId'
      preLoaderRoute: typeof ConsoleOrganizationsOrganizationIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleAuditRoute: typeof ConsoleAuditRoute
  ConsoleNotificationsRoute: typeof ConsoleNotificationsRoute
  ConsolePreferencesRoute: typeof ConsolePreferencesRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleUsersRoute: typeof ConsoleUsersRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleOrganizationsOrganizationIdRoute: typeof ConsoleOrganizationsOrganizationIdRoute
  ConsoleOrganizationsIndexRoute: typeof ConsoleOrganizationsIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAuditRoute: ConsoleAuditRoute,
  ConsoleNotificationsRoute: ConsoleNotificationsRoute,
  ConsolePreferencesRoute: ConsolePreferencesRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleUsersRoute: ConsoleUsersRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleOrganizationsOrganizationIdRoute:
    ConsoleOrganizationsOrganizationIdRoute,
  ConsoleOrganizationsIndexRoute: ConsoleOrganizationsIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
