// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/zgiai/luas/api/internal/app"
	"github.com/zgiai/luas/api/internal/infra/config"
	"github.com/zgiai/luas/api/internal/infra/database"
	"github.com/zgiai/luas/api/internal/infra/email"
	"github.com/zgiai/luas/api/internal/infra/events"
	"github.com/zgiai/luas/api/internal/infra/migration"
	"github.com/zgiai/luas/api/internal/infra/storage"
	"github.com/zgiai/luas/api/internal/modules/apikey"
	"github.com/zgiai/luas/api/internal/modules/asset"
	"github.com/zgiai/luas/api/internal/modules/audit"
	"github.com/zgiai/luas/api/internal/modules/notification"
	"github.com/zgiai/luas/api/internal/modules/organization"
	"github.com/zgiai/luas/api/internal/modules/permission"
	"github.com/zgiai/luas/api/internal/modules/setting"
	"github.com/zgiai/luas/api/internal/modules/usage"
	"github.com/zgiai/luas/api/internal/modules/user"
	"github.com/zgiai/luas/api/internal/modules/webhook"
	"github.com/zgiai/luas/api/internal/starter"
)

// Injectors from wire.go:

// InitApplication initializes the entire application with all dependencies.
// This is the single entry point for Wire DI.
func InitApplication() (*app.Application, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	service := email.NewService(configConfig)
	eventBus := events.NewEventBus()
	repository := migration.NewDatabaseRepositoryProvider(db)
	migrator := migration.NewMigratorProvider(repository, db, eventBus)
	auditRepository := audit.NewRepository(db)
	auditService := audit.NewService(auditRepository)
	handler := audit.NewHandler(auditService)
	apikeyRepository := apikey.NewRepository(db)
	apikeyService := apikey.NewService(apikeyRepository)
	apikeyHandler := apikey.NewHandler(apikeyService)
	userRepository := user.NewRepository(db)
	sessionService := user.NewSessionService(userRepository, configConfig)
	userMailer := user.NewUserMailer(service)
	accountDeletionPolicy := user.NewAccountDeletionPolicy()
	userService := user.NewService(userRepository, userRepository, sessionService, eventBus, userMailer, accountDeletionPolicy)
	authAbuseGuard := user.NewAuthAbuseGuard(configConfig)
	browserSessionAdapter := user.NewBrowserSessionAdapter(userService, userService, sessionService, configConfig)
	userHandler := user.NewHandler(userService, userService, userService, sessionService, userMailer, authAbuseGuard, browserSessionAdapter)
	organizationRepository := organization.NewRepository(db)
	invitationMailer := organization.NewInvitationMailer(service)
	invitationPolicy := organization.NewInvitationPolicy(configConfig)
	organizationService := organization.NewService(organizationRepository, organizationRepository, invitationMailer, invitationPolicy)
	contextResolver := organization.NewContextResolver(organizationService)
	organizationHandler := organization.NewHandler(organizationService, contextResolver, accountDeletionPolicy)
	permissionRepository := permission.NewRepository(db)
	catalog, err := permission.NewDefaultCatalog()
	if err != nil {
		return nil, err
	}
	permissionService := permission.NewService(permissionRepository, catalog)
	guard := permission.NewGuard(permissionService)
	permissionHandler := permission.NewHandler(permissionService, guard)
	notificationRepository := notification.NewRepository(db)
	emailSender := notification.ProvideEmailSender(service)
	eventPublisher := notification.ProvideEventPublisher(eventBus)
	notificationService := notification.NewService(configConfig, notificationRepository, emailSender, eventPublisher)
	notificationHandler := notification.NewHandler(notificationService)
	assetRepository := asset.NewRepository(db)
	objectStore, err := storage.NewObjectStore(configConfig)
	if err != nil {
		return nil, err
	}
	contentInspector := asset.NewContentInspector()
	transferSigner, err := asset.NewTransferSigner(configConfig)
	if err != nil {
		return nil, err
	}
	assetService := asset.NewService(configConfig, assetRepository, objectStore, contentInspector, transferSigner)
	assetHandler := asset.NewHandler(assetService, accountDeletionPolicy)
	settingCatalog, err := setting.NewDefaultCatalog()
	if err != nil {
		return nil, err
	}
	settingRepository := setting.NewRepository(db)
	settingService := setting.NewService(settingCatalog, settingRepository, configConfig)
	settingHandler := setting.NewHandler(settingService, accountDeletionPolicy)
	usageCatalog, err := usage.NewDefaultCatalog()
	if err != nil {
		return nil, err
	}
	usageRepository := usage.NewRepository(db)
	usageService := usage.NewService(usageCatalog, usageRepository, configConfig)
	usageHandler := usage.NewHandler(usageService, accountDeletionPolicy)
	webhookCatalog, err := webhook.NewDefaultCatalog()
	if err != nil {
		return nil, err
	}
	webhookRepository := webhook.NewRepository(db)
	secretProtector, err := webhook.NewSecretProtector(configConfig)
	if err != nil {
		return nil, err
	}
	targetPolicy := webhook.NewTargetPolicy(configConfig)
	sender := webhook.NewSender(configConfig, targetPolicy)
	webhookService := webhook.NewService(webhookCatalog, webhookRepository, secretProtector, targetPolicy, sender, configConfig)
	webhookHandler := webhook.NewHandler(webhookService)
	registry, err := starter.NewConfiguredRegistry(configConfig, migrator, handler, apikeyHandler, userHandler, organizationHandler, permissionHandler, notificationHandler, assetHandler, settingHandler, usageHandler, webhookHandler)
	if err != nil {
		return nil, err
	}
	application := &app.Application{
		Config:                 configConfig,
		DB:                     db,
		EmailService:           service,
		EventBus:               eventBus,
		Migrator:               migrator,
		Starters:               registry,
		AuditRecorder:          auditService,
		AuditMaintainer:        auditService,
		AuthenticationSessions: sessionService,
		NotificationPublisher:  notificationService,
		NotificationDispatcher: notificationService,
		AssetReader:            assetService,
		AssetMaintainer:        assetService,
		SettingReader:          settingService,
		AppSettingWriter:       settingService,
		UsageReader:            usageService,
		UsageRecorder:          usageService,
		UsageConsumer:          usageService,
		UsageQuotaWriter:       usageService,
		UsageMaintainer:        usageService,
		WebhookPublisher:       webhookService,
		WebhookDispatcher:      webhookService,
		WebhookTester:          webhookService,
		WebhookMaintainer:      webhookService,
	}
	return application, nil
}

// InitApplicationWithConfig initializes the application from an already validated startup snapshot.
// Production bootstraps use it to share that snapshot with pre-Wire services; tests use it to reuse
// the same dependency graph without reading process configuration.
func InitApplicationWithConfig(cfg *config.Config) (*app.Application, error) {
	db, err := database.NewDB(cfg)
	if err != nil {
		return nil, err
	}
	service := email.NewService(cfg)
	eventBus := events.NewEventBus()
	repository := migration.NewDatabaseRepositoryProvider(db)
	migrator := migration.NewMigratorProvider(repository, db, eventBus)
	auditRepository := audit.NewRepository(db)
	auditService := audit.NewService(auditRepository)
	handler := audit.NewHandler(auditService)
	apikeyRepository := apikey.NewRepository(db)
	apikeyService := apikey.NewService(apikeyRepository)
	apikeyHandler := apikey.NewHandler(apikeyService)
	userRepository := user.NewRepository(db)
	sessionService := user.NewSessionService(userRepository, cfg)
	userMailer := user.NewUserMailer(service)
	accountDeletionPolicy := user.NewAccountDeletionPolicy()
	userService := user.NewService(userRepository, userRepository, sessionService, eventBus, userMailer, accountDeletionPolicy)
	authAbuseGuard := user.NewAuthAbuseGuard(cfg)
	browserSessionAdapter := user.NewBrowserSessionAdapter(userService, userService, sessionService, cfg)
	userHandler := user.NewHandler(userService, userService, userService, sessionService, userMailer, authAbuseGuard, browserSessionAdapter)
	organizationRepository := organization.NewRepository(db)
	invitationMailer := organization.NewInvitationMailer(service)
	invitationPolicy := organization.NewInvitationPolicy(cfg)
	organizationService := organization.NewService(organizationRepository, organizationRepository, invitationMailer, invitationPolicy)
	contextResolver := organization.NewContextResolver(organizationService)
	organizationHandler := organization.NewHandler(organizationService, contextResolver, accountDeletionPolicy)
	permissionRepository := permission.NewRepository(db)
	catalog, err := permission.NewDefaultCatalog()
	if err != nil {
		return nil, err
	}
	permissionService := permission.NewService(permissionRepository, catalog)
	guard := permission.NewGuard(permissionService)
	permissionHandler := permission.NewHandler(permissionService, guard)
	notificationRepository := notification.NewRepository(db)
	emailSender := notification.ProvideEmailSender(service)
	eventPublisher := notification.ProvideEventPublisher(eventBus)
	notificationService := notification.NewService(cfg, notificationRepository, emailSender, eventPublisher)
	notificationHandler := notification.NewHandler(notificationService)
	assetRepository := asset.NewRepository(db)
	objectStore, err := storage.NewObjectStore(cfg)
	if err != nil {
		return nil, err
	}
	contentInspector := asset.NewContentInspector()
	transferSigner, err := asset.NewTransferSigner(cfg)
	if err != nil {
		return nil, err
	}
	assetService := asset.NewService(cfg, assetRepository, objectStore, contentInspector, transferSigner)
	assetHandler := asset.NewHandler(assetService, accountDeletionPolicy)
	settingCatalog, err := setting.NewDefaultCatalog()
	if err != nil {
		return nil, err
	}
	settingRepository := setting.NewRepository(db)
	settingService := setting.NewService(settingCatalog, settingRepository, cfg)
	settingHandler := setting.NewHandler(settingService, accountDeletionPolicy)
	usageCatalog, err := usage.NewDefaultCatalog()
	if err != nil {
		return nil, err
	}
	usageRepository := usage.NewRepository(db)
	usageService := usage.NewService(usageCatalog, usageRepository, cfg)
	usageHandler := usage.NewHandler(usageService, accountDeletionPolicy)
	webhookCatalog, err := webhook.NewDefaultCatalog()
	if err != nil {
		return nil, err
	}
	webhookRepository := webhook.NewRepository(db)
	secretProtector, err := webhook.NewSecretProtector(cfg)
	if err != nil {
		return nil, err
	}
	targetPolicy := webhook.NewTargetPolicy(cfg)
	sender := webhook.NewSender(cfg, targetPolicy)
	webhookService := webhook.NewService(webhookCatalog, webhookRepository, secretProtector, targetPolicy, sender, cfg)
	webhookHandler := webhook.NewHandler(webhookService)
	registry, err := starter.NewConfiguredRegistry(cfg, migrator, handler, apikeyHandler, userHandler, organizationHandler, permissionHandler, notificationHandler, assetHandler, settingHandler, usageHandler, webhookHandler)
	if err != nil {
		return nil, err
	}
	application := &app.Application{
		Config:                 cfg,
		DB:                     db,
		EmailService:           service,
		EventBus:               eventBus,
		Migrator:               migrator,
		Starters:               registry,
		AuditRecorder:          auditService,
		AuditMaintainer:        auditService,
		AuthenticationSessions: sessionService,
		NotificationPublisher:  notificationService,
		NotificationDispatcher: notificationService,
		AssetReader:            assetService,
		AssetMaintainer:        assetService,
		SettingReader:          settingService,
		AppSettingWriter:       settingService,
		UsageReader:            usageService,
		UsageRecorder:          usageService,
		UsageConsumer:          usageService,
		UsageQuotaWriter:       usageService,
		UsageMaintainer:        usageService,
		WebhookPublisher:       webhookService,
		WebhookDispatcher:      webhookService,
		WebhookTester:          webhookService,
		WebhookMaintainer:      webhookService,
	}
	return application, nil
}
