// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/zgiai/luas/api/internal/app"
	"github.com/zgiai/luas/api/internal/infra/config"
	"github.com/zgiai/luas/api/internal/infra/database"
	"github.com/zgiai/luas/api/internal/infra/email"
	"github.com/zgiai/luas/api/internal/infra/events"
	"github.com/zgiai/luas/api/internal/infra/jwt"
	"github.com/zgiai/luas/api/internal/infra/migration"
	"github.com/zgiai/luas/api/internal/modules/apikey"
	"github.com/zgiai/luas/api/internal/modules/audit"
	"github.com/zgiai/luas/api/internal/modules/organization"
	"github.com/zgiai/luas/api/internal/modules/user"
	"github.com/zgiai/luas/api/internal/starter"
)

// Injectors from wire.go:

// InitApplication initializes the entire application with all dependencies.
// This is the single entry point for Wire DI.
func InitApplication() (*app.Application, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	service := email.NewService(configConfig)
	eventBus := events.NewEventBus()
	repository := migration.NewDatabaseRepositoryProvider(db)
	migrator := migration.NewMigratorProvider(repository, db, eventBus)
	auditRepository := audit.NewRepository(db)
	auditService := audit.NewService(auditRepository)
	handler := audit.NewHandler(auditService)
	apikeyRepository := apikey.NewRepository(db)
	apikeyService := apikey.NewService(apikeyRepository)
	apikeyHandler := apikey.NewHandler(apikeyService)
	userRepository := user.NewRepository(db)
	jwtService := jwt.NewService(configConfig)
	userMailer := user.NewUserMailer(service)
	accountDeletionPolicy := user.NewAccountDeletionPolicy()
	userService := user.NewService(userRepository, userRepository, jwtService, eventBus, userMailer, accountDeletionPolicy)
	authAbuseGuard := user.NewAuthAbuseGuard(configConfig)
	userHandler := user.NewHandler(userService, userService, userService, jwtService, userMailer, authAbuseGuard)
	organizationRepository := organization.NewRepository(db)
	organizationService := organization.NewService(organizationRepository)
	organizationHandler := organization.NewHandler(organizationService, accountDeletionPolicy)
	registry, err := starter.NewConfiguredRegistry(configConfig, migrator, handler, apikeyHandler, userHandler, organizationHandler)
	if err != nil {
		return nil, err
	}
	application := &app.Application{
		Config:       configConfig,
		DB:           db,
		EmailService: service,
		EventBus:     eventBus,
		Migrator:     migrator,
		Starters:     registry,
	}
	return application, nil
}

// InitApplicationWithConfig initializes the application from an already validated startup snapshot.
// Production bootstraps use it to share that snapshot with pre-Wire services; tests use it to reuse
// the same dependency graph without reading process configuration.
func InitApplicationWithConfig(cfg *config.Config) (*app.Application, error) {
	db, err := database.NewDB(cfg)
	if err != nil {
		return nil, err
	}
	service := email.NewService(cfg)
	eventBus := events.NewEventBus()
	repository := migration.NewDatabaseRepositoryProvider(db)
	migrator := migration.NewMigratorProvider(repository, db, eventBus)
	auditRepository := audit.NewRepository(db)
	auditService := audit.NewService(auditRepository)
	handler := audit.NewHandler(auditService)
	apikeyRepository := apikey.NewRepository(db)
	apikeyService := apikey.NewService(apikeyRepository)
	apikeyHandler := apikey.NewHandler(apikeyService)
	userRepository := user.NewRepository(db)
	jwtService := jwt.NewService(cfg)
	userMailer := user.NewUserMailer(service)
	accountDeletionPolicy := user.NewAccountDeletionPolicy()
	userService := user.NewService(userRepository, userRepository, jwtService, eventBus, userMailer, accountDeletionPolicy)
	authAbuseGuard := user.NewAuthAbuseGuard(cfg)
	userHandler := user.NewHandler(userService, userService, userService, jwtService, userMailer, authAbuseGuard)
	organizationRepository := organization.NewRepository(db)
	organizationService := organization.NewService(organizationRepository)
	organizationHandler := organization.NewHandler(organizationService, accountDeletionPolicy)
	registry, err := starter.NewConfiguredRegistry(cfg, migrator, handler, apikeyHandler, userHandler, organizationHandler)
	if err != nil {
		return nil, err
	}
	application := &app.Application{
		Config:       cfg,
		DB:           db,
		EmailService: service,
		EventBus:     eventBus,
		Migrator:     migrator,
		Starters:     registry,
	}
	return application, nil
}
