#!/usr/bin/env python3

"""Render the skill counts and tables in .agents/skills/README.md from skill metadata.

Each table row comes from the skill directory name and the quoted `short_description` in its
agents/openai.yaml, so the index cannot drift from the skills that ship.

  python3 .agents/skills/scripts/render-skill-index.py --check   # fail when the README is stale
  python3 .agents/skills/scripts/render-skill-index.py --write   # regenerate it
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
README = ROOT / ".agents" / "skills" / "README.md"
SCOPES = (
    ("Root", ROOT / ".agents" / "skills"),
    ("API", ROOT / "api" / ".agents" / "skills"),
    ("Web", ROOT / "web" / ".agents" / "skills"),
)
SHORT_DESCRIPTION = re.compile(r'^\s*short_description:\s*"(?P<text>[^"]+)"\s*$', re.MULTILINE)
REGION = re.compile(
    r"(<!-- skill-index:(?P<name>[a-z]+):begin \(generated by render-skill-index\.py; do not edit\) -->\n)"
    r"(?P<body>.*?)"
    r"(<!-- skill-index:(?P=name):end -->)",
    re.DOTALL,
)


def skills(directory: Path) -> list[tuple[str, str]]:
    rows = []
    for skill in sorted(path for path in directory.iterdir() if (path / "SKILL.md").is_file()):
        metadata = skill / "agents" / "openai.yaml"
        match = SHORT_DESCRIPTION.search(metadata.read_text(encoding="utf-8")) if metadata.is_file() else None
        if match is None:
            raise SystemExit(f"{metadata.relative_to(ROOT)} needs a quoted interface.short_description")
        rows.append((skill.name, match.group("text")))
    return rows


def render() -> dict[str, str]:
    catalog = {scope: skills(directory) for scope, directory in SCOPES}
    root, api, web = (len(catalog[scope]) for scope, _ in SCOPES)
    scope = "\n".join(
        [
            "| Working directory | Repository skills available |",
            "|---|---|",
            f"| Repository root | {root} root skills |",
            f"| `api/` | {root} root + {api} API skills |",
            f"| `web/` | {root} root + {web} Web skills |",
            f"| `admin/` | {root} root skills + local `AGENTS.md` |",
            "",
            f"The repository ships {root + api + web} skills in total.",
            "",
        ]
    )
    tables = []
    for name, _ in SCOPES:
        tables += [f"### {name} Skills", "", "| Skill | Job |", "|---|---|"]
        tables += [f"| `{skill}` | {job} |" for skill, job in catalog[name]]
        tables.append("")
    return {"scope": scope, "tables": "\n".join(tables)}


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    if mode not in ("--check", "--write"):
        print(__doc__, file=sys.stderr)
        return 2
    content = README.read_text(encoding="utf-8")
    generated = render()
    found = set()

    def replace(match: re.Match[str]) -> str:
        found.add(match.group("name"))
        return match.group(1) + generated[match.group("name")] + match.group(4)

    updated = REGION.sub(replace, content)
    missing = set(generated) - found
    if missing:
        print(f"{README.relative_to(ROOT)} lacks skill-index regions: {', '.join(sorted(missing))}", file=sys.stderr)
        return 1
    if mode == "--write":
        README.write_text(updated, encoding="utf-8")
        return 0
    if updated != content:
        print(
            f"{README.relative_to(ROOT)} skill index is stale; run "
            "python3 .agents/skills/scripts/render-skill-index.py --write",
            file=sys.stderr,
        )
        return 1
    print(f"Skill index check passed ({sum(1 for _ in REGION.finditer(content))} generated regions).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
