// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/zgiai/zgo/internal/app"
	"github.com/zgiai/zgo/internal/infra/config"
	"github.com/zgiai/zgo/internal/infra/database"
	"github.com/zgiai/zgo/internal/infra/email"
	"github.com/zgiai/zgo/internal/infra/events"
	"github.com/zgiai/zgo/internal/infra/jwt"
	"github.com/zgiai/zgo/internal/infra/migration"
	"github.com/zgiai/zgo/internal/infra/storage"
	"github.com/zgiai/zgo/internal/modules/event"
	"github.com/zgiai/zgo/internal/modules/ingest"
	"github.com/zgiai/zgo/internal/modules/issue"
	"github.com/zgiai/zgo/internal/modules/permission"
	"github.com/zgiai/zgo/internal/modules/project"
	"github.com/zgiai/zgo/internal/modules/user"
)

// Injectors from wire.go:

// InitApplication initializes the entire application with all dependencies.
// This is the single entry point for Wire DI.
func InitApplication() (*app.Application, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	service := jwt.NewService(configConfig)
	emailService := email.NewService(configConfig)
	eventBus := events.NewEventBus()
	repository := migration.NewDatabaseRepositoryProvider(db)
	migrator := migration.NewMigratorProvider(repository, db, eventBus)
	userRepository := user.NewRepository(db)
	userService := user.NewService(userRepository, service, eventBus)
	handler := user.NewHandler(userService)
	permissionRepository := permission.NewRepository(db)
	permissionService := permission.NewService(permissionRepository)
	permissionHandler := permission.NewHandler(permissionService)
	projectRepository := project.NewRepository(db)
	projectService := project.NewService(projectRepository)
	projectHandler := project.NewHandler(projectService)
	conn, err := storage.NewCHClient(configConfig)
	if err != nil {
		return nil, err
	}
	eventRepository, err := event.NewRepository(conn)
	if err != nil {
		return nil, err
	}
	eventService := event.NewService(eventRepository)
	ingestHandler := ingest.NewHandler(projectService, eventService)
	issueRepository, err := issue.NewRepository(conn)
	if err != nil {
		return nil, err
	}
	issueService := issue.NewService(issueRepository)
	issueHandler := issue.NewHandler(issueService)
	handlers := &app.Handlers{
		User:       handler,
		Permission: permissionHandler,
		Project:    projectHandler,
		Ingest:     ingestHandler,
		Issue:      issueHandler,
	}
	application := &app.Application{
		Config:       configConfig,
		DB:           db,
		JWTService:   service,
		EmailService: emailService,
		EventBus:     eventBus,
		Migrator:     migrator,
		Handlers:     handlers,
	}
	return application, nil
}
