// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/zgiai/zgo/internal/app"
	"github.com/zgiai/zgo/internal/infra/config"
	"github.com/zgiai/zgo/internal/infra/database"
	"github.com/zgiai/zgo/internal/infra/email"
	"github.com/zgiai/zgo/internal/infra/events"
	"github.com/zgiai/zgo/internal/infra/jwt"
	"github.com/zgiai/zgo/internal/infra/migration"
	"github.com/zgiai/zgo/internal/modules/apikey"
	"github.com/zgiai/zgo/internal/modules/user"
	"github.com/zgiai/zgo/internal/starter"
)

// Injectors from wire.go:

// InitApplication initializes the entire application with all dependencies.
// This is the single entry point for Wire DI.
func InitApplication() (*app.Application, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	service := email.NewService(configConfig)
	eventBus := events.NewEventBus()
	repository := migration.NewDatabaseRepositoryProvider(db)
	migrator := migration.NewMigratorProvider(repository, db, eventBus)
	apikeyRepository := apikey.NewRepository(db)
	apikeyService := apikey.NewService(apikeyRepository)
	handler := apikey.NewHandler(apikeyService)
	userRepository := user.NewRepository(db)
	jwtService := jwt.NewService(configConfig)
	userService := user.NewService(userRepository, jwtService, eventBus)
	userHandler := user.NewHandler(userService, userService, userService, jwtService)
	registry, err := starter.NewDefaultRegistry(handler, userHandler)
	if err != nil {
		return nil, err
	}
	application := &app.Application{
		Config:       configConfig,
		DB:           db,
		EmailService: service,
		EventBus:     eventBus,
		Migrator:     migrator,
		Starters:     registry,
	}
	return application, nil
}
