package commands

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/zgiai/luas/api/internal/starter"
)

const (
	starterCatalogReadme    = "../../../modules/README.md"
	starterCatalogBegin     = "<!-- starter-catalog:begin (generated by `make starter-catalog`; do not edit) -->\n"
	starterCatalogEnd       = "<!-- starter-catalog:end -->"
	updateStarterCatalogEnv = "LUAS_UPDATE_STARTER_CATALOG"
)

// TestModulesReadmeStarterCatalogIsGenerated keeps the README table identical to the manifests.
// Regenerate it with `make starter-catalog`.
func TestModulesReadmeStarterCatalogIsGenerated(t *testing.T) {
	path := filepath.FromSlash(starterCatalogReadme)
	raw, err := os.ReadFile(path)
	require.NoError(t, err)
	content := string(raw)

	begin := strings.Index(content, starterCatalogBegin)
	end := strings.Index(content, starterCatalogEnd)
	require.True(t, begin >= 0 && end > begin, "%s must contain the starter-catalog markers", path)
	current := content[begin+len(starterCatalogBegin) : end]
	generated := starter.MarkdownCatalog()

	if os.Getenv(updateStarterCatalogEnv) == "1" {
		updated := content[:begin+len(starterCatalogBegin)] + generated + content[end:]
		require.NoError(t, os.WriteFile(path, []byte(updated), 0o644))
		return
	}
	require.Equal(t, generated, current,
		"internal/modules/README.md starter table is stale; run `cd api && make starter-catalog`")
}
