import type { components } from '@/http/generated/openapi';

type OpenAPIErrorCode = components['schemas']['ErrorCode'];

export const ApiErrorCode = {
  COMMON_INTERNAL: 'COMMON.INTERNAL',
  COMMON_INVALID_INPUT: 'COMMON.INVALID_INPUT',
  COMMON_VALIDATION_FAILED: 'COMMON.VALIDATION_FAILED',
  COMMON_RATE_LIMITED: 'COMMON.RATE_LIMITED',
  COMMON_REQUEST_TOO_LARGE: 'COMMON.REQUEST_TOO_LARGE',
  COMMON_TIMEOUT: 'COMMON.TIMEOUT',
  COMMON_SERVICE_UNAVAILABLE: 'COMMON.SERVICE_UNAVAILABLE',
  COMMON_NOT_FOUND: 'COMMON.NOT_FOUND',
  COMMON_CONFLICT: 'COMMON.CONFLICT',

  AUTH_UNAUTHORIZED: 'AUTH.UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH.FORBIDDEN',
  AUTH_INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DISABLED: 'AUTH.ACCOUNT_DISABLED',
  AUTH_PASSWORD_RESET_TOKEN_INVALID: 'AUTH.PASSWORD_RESET_TOKEN_INVALID',
  AUTH_PASSWORD_RESET_TOKEN_EXPIRED: 'AUTH.PASSWORD_RESET_TOKEN_EXPIRED',

  USER_NOT_FOUND: 'USER.NOT_FOUND',
  USER_EMAIL_ALREADY_EXISTS: 'USER.EMAIL_ALREADY_EXISTS',
  USER_USERNAME_ALREADY_EXISTS: 'USER.USERNAME_ALREADY_EXISTS',

  API_KEY_NOT_FOUND: 'API_KEY.NOT_FOUND',
  API_KEY_INVALID: 'API_KEY.INVALID',
  API_KEY_EXPIRED: 'API_KEY.EXPIRED',
  API_KEY_REVOKED: 'API_KEY.REVOKED',

  ORGANIZATION_CONTEXT_REQUIRED: 'ORGANIZATION.CONTEXT_REQUIRED',
  ORGANIZATION_CONTEXT_INVALID: 'ORGANIZATION.CONTEXT_INVALID',
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION.NOT_FOUND',
  ORGANIZATION_SLUG_ALREADY_EXISTS: 'ORGANIZATION.SLUG_ALREADY_EXISTS',
  ORGANIZATION_INVITATION_NOT_FOUND: 'ORGANIZATION.INVITATION.NOT_FOUND',
  ORGANIZATION_INVITATION_INVALID: 'ORGANIZATION.INVITATION.INVALID',
  ORGANIZATION_INVITATION_EXPIRED: 'ORGANIZATION.INVITATION.EXPIRED',
  ORGANIZATION_INVITATION_ALREADY_PENDING: 'ORGANIZATION.INVITATION.ALREADY_PENDING',
  ORGANIZATION_INVITATION_EMAIL_MISMATCH: 'ORGANIZATION.INVITATION.EMAIL_MISMATCH',
  ORGANIZATION_MEMBER_ALREADY_EXISTS: 'ORGANIZATION.MEMBER_ALREADY_EXISTS',
  ORGANIZATION_MEMBER_NOT_FOUND: 'ORGANIZATION.MEMBER_NOT_FOUND',
  ORGANIZATION_OWNERSHIP_TRANSFER_REQUIRED: 'ORGANIZATION.OWNERSHIP_TRANSFER_REQUIRED',
  ORGANIZATION_OWNERSHIP_TRANSFER_TARGET_INVALID: 'ORGANIZATION.OWNERSHIP_TRANSFER_TARGET_INVALID',
  ORGANIZATION_MEMBERSHIP_EXIT_REQUIRED: 'ORGANIZATION.MEMBERSHIP_EXIT_REQUIRED',

  PERMISSION_DENIED: 'PERMISSION.DENIED',
  PERMISSION_UNKNOWN: 'PERMISSION.UNKNOWN',
  PERMISSION_ROLE_NOT_FOUND: 'PERMISSION.ROLE_NOT_FOUND',
  PERMISSION_ROLE_SLUG_ALREADY_EXISTS: 'PERMISSION.ROLE_SLUG_ALREADY_EXISTS',
  ROLE_NOT_FOUND: 'ROLE.NOT_FOUND', // Deprecated legacy server code.

  NOTIFICATION_NOT_FOUND: 'NOTIFICATION.NOT_FOUND',
  NOTIFICATION_IDEMPOTENCY_CONFLICT: 'NOTIFICATION.IDEMPOTENCY_CONFLICT',
  NOTIFICATION_INVALID_CHANNEL: 'NOTIFICATION.INVALID_CHANNEL',

  ASSET_NOT_FOUND: 'ASSET.NOT_FOUND',
  ASSET_NOT_READY: 'ASSET.NOT_READY',
  ASSET_IDEMPOTENCY_CONFLICT: 'ASSET.IDEMPOTENCY_CONFLICT',
  ASSET_CLEANUP_REQUIRED: 'ASSET.CLEANUP_REQUIRED',
  ASSET_UPLOAD_EXPIRED: 'ASSET.UPLOAD_EXPIRED',
  ASSET_SIZE_EXCEEDED: 'ASSET.SIZE_EXCEEDED',
  ASSET_INVALID_MEDIA_TYPE: 'ASSET.INVALID_MEDIA_TYPE',

  SETTING_NOT_FOUND: 'SETTING.NOT_FOUND',
  SETTING_INVALID_VALUE: 'SETTING.INVALID_VALUE',
  SETTING_VERSION_CONFLICT: 'SETTING.VERSION_CONFLICT',
  SETTING_PRECONDITION_REQUIRED: 'SETTING.PRECONDITION_REQUIRED',

  USAGE_METRIC_NOT_FOUND: 'USAGE.METRIC_NOT_FOUND',
  USAGE_INVALID_EVENT: 'USAGE.INVALID_EVENT',
  USAGE_EVENT_OUTSIDE_WINDOW: 'USAGE.EVENT_OUTSIDE_WINDOW',
  USAGE_IDEMPOTENCY_CONFLICT: 'USAGE.IDEMPOTENCY_CONFLICT',
  USAGE_QUOTA_EXCEEDED: 'USAGE.QUOTA_EXCEEDED',
  USAGE_QUOTA_VERSION_CONFLICT: 'USAGE.QUOTA_VERSION_CONFLICT',
  USAGE_PRECONDITION_REQUIRED: 'USAGE.PRECONDITION_REQUIRED',

  WEBHOOK_ENDPOINT_NOT_FOUND: 'WEBHOOK.ENDPOINT_NOT_FOUND',
  WEBHOOK_DELIVERY_NOT_FOUND: 'WEBHOOK.DELIVERY_NOT_FOUND',
  WEBHOOK_INVALID_EVENT_TYPE: 'WEBHOOK.INVALID_EVENT_TYPE',
  WEBHOOK_INVALID_TARGET: 'WEBHOOK.INVALID_TARGET',
  WEBHOOK_IDEMPOTENCY_CONFLICT: 'WEBHOOK.IDEMPOTENCY_CONFLICT',
  WEBHOOK_ENDPOINT_VERSION_CONFLICT: 'WEBHOOK.ENDPOINT_VERSION_CONFLICT',
  WEBHOOK_PRECONDITION_REQUIRED: 'WEBHOOK.PRECONDITION_REQUIRED',
  WEBHOOK_REPLAY_NOT_ALLOWED: 'WEBHOOK.REPLAY_NOT_ALLOWED',
} as const satisfies Readonly<Record<string, OpenAPIErrorCode>>;

export type ApiErrorCodeValue = OpenAPIErrorCode;

export const ClientErrorCode = {
  FETCH_ERROR: 'CLIENT.FETCH_ERROR',
  INVALID_RESPONSE: 'CLIENT.INVALID_RESPONSE',
  NETWORK_ERROR: 'CLIENT.NETWORK_ERROR',
  TIMEOUT: 'CLIENT.TIMEOUT',
  UNKNOWN: 'CLIENT.UNKNOWN',
} as const;

export type ClientErrorCodeValue = (typeof ClientErrorCode)[keyof typeof ClientErrorCode];

export type ErrorCodeValue = ApiErrorCodeValue | ClientErrorCodeValue | string;

export const HttpStatusErrorCodeMap: Record<number, ApiErrorCodeValue> = {
  400: ApiErrorCode.COMMON_INVALID_INPUT,
  401: ApiErrorCode.AUTH_UNAUTHORIZED,
  403: ApiErrorCode.AUTH_FORBIDDEN,
  404: ApiErrorCode.COMMON_NOT_FOUND,
  409: ApiErrorCode.COMMON_CONFLICT,
  413: ApiErrorCode.COMMON_REQUEST_TOO_LARGE,
  422: ApiErrorCode.COMMON_VALIDATION_FAILED,
  429: ApiErrorCode.COMMON_RATE_LIMITED,
  500: ApiErrorCode.COMMON_INTERNAL,
  503: ApiErrorCode.COMMON_SERVICE_UNAVAILABLE,
};

const LegacyErrorCodeMap: Record<string, ApiErrorCodeValue | ClientErrorCodeValue> = {
  SYS_001: ClientErrorCode.UNKNOWN,
  SYS_002: ClientErrorCode.NETWORK_ERROR,
  SYS_003: ClientErrorCode.TIMEOUT,
  SYS_500: ApiErrorCode.COMMON_INTERNAL,
  SYS_503: ApiErrorCode.COMMON_SERVICE_UNAVAILABLE,

  AUTH_401: ApiErrorCode.AUTH_UNAUTHORIZED,
  AUTH_403: ApiErrorCode.AUTH_FORBIDDEN,
  AUTH_001: ApiErrorCode.AUTH_UNAUTHORIZED,
  AUTH_002: ApiErrorCode.AUTH_INVALID_CREDENTIALS,
  AUTH_003: ApiErrorCode.USER_NOT_FOUND,
  AUTH_004: ApiErrorCode.AUTH_UNAUTHORIZED,

  VAL_400: ApiErrorCode.COMMON_INVALID_INPUT,
  VAL_001: ApiErrorCode.COMMON_VALIDATION_FAILED,
  VAL_002: ApiErrorCode.COMMON_VALIDATION_FAILED,

  BIZ_404: ApiErrorCode.COMMON_NOT_FOUND,
  BIZ_001: ApiErrorCode.COMMON_CONFLICT,
  BIZ_002: ApiErrorCode.COMMON_INTERNAL,
  BIZ_003: ApiErrorCode.COMMON_RATE_LIMITED,
};

export function normalizeLegacyErrorCode(code: unknown): ErrorCodeValue | undefined {
  if (typeof code !== 'string') {
    return undefined;
  }

  return LegacyErrorCodeMap[code] ?? code;
}
