package migrations

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"gorm.io/gorm"

	"github.com/zgiai/luas/api/internal/infra/migration"
	testplatform "github.com/zgiai/luas/api/internal/infra/testing"
)

// updateGoldenSchemaEnv regenerates testdata/schema.golden.sql instead of comparing against it.
// Only set it in a change that intentionally adds a new migration.
const updateGoldenSchemaEnv = "LUAS_UPDATE_GOLDEN_SCHEMA"

const goldenSchemaPath = "testdata/schema.golden.sql"

// TestMigrationsProduceGoldenSchema pins the schema that a fresh PostgreSQL database receives from
// every registered migration. Versioned migrations are history: this test fails when a change to a
// module persistence struct, GORM, or a migration silently alters what an existing migration creates.
func TestMigrationsProduceGoldenSchema(t *testing.T) {
	db := testplatform.OpenPostgres(t, nil)
	migrateAll(t, db)

	actual := dumpSchema(t, db)
	if os.Getenv(updateGoldenSchemaEnv) == "1" {
		require.NoError(t, os.MkdirAll(filepath.Dir(goldenSchemaPath), 0o755))
		require.NoError(t, os.WriteFile(goldenSchemaPath, []byte(actual), 0o600))
		t.Logf("updated %s", goldenSchemaPath)
		return
	}

	expected, err := os.ReadFile(goldenSchemaPath)
	require.NoError(t, err, "missing golden schema; run with %s=1 to create it", updateGoldenSchemaEnv)
	require.Equal(t, string(expected), actual,
		"fresh migration schema drifted from %s; existing migrations must not change what they create", goldenSchemaPath)
}

// TestMigrationsRollBackToEmptySchema proves every Down reverses its Up so reset leaves only the
// migration repository behind.
func TestMigrationsRollBackToEmptySchema(t *testing.T) {
	db := testplatform.OpenPostgres(t, nil)
	migrator := migrateAll(t, db)

	_, err := migrator.Reset(false)
	require.NoError(t, err)

	var tables []string
	require.NoError(t, db.Raw(`
		SELECT table_name FROM information_schema.tables
		WHERE table_schema = current_schema() AND table_type = 'BASE TABLE'
		ORDER BY table_name
	`).Scan(&tables).Error)
	require.Equal(t, []string{"migrations"}, tables)
}

func migrateAll(t *testing.T, db *gorm.DB) *migration.Migrator {
	t.Helper()
	migrator := migration.NewMigrator(migration.NewDatabaseRepository(db, "migrations"), db, nil)
	migrator.RegisterMany(All())
	_, err := migrator.Run(migration.MigratorOptions{})
	require.NoError(t, err)
	return migrator
}

// dumpSchema renders a deterministic, version-stable description of the current schema. NOT NULL
// constraint rows (PostgreSQL 18+) are excluded because nullability is already captured per column.
func dumpSchema(t *testing.T, db *gorm.DB) string {
	t.Helper()
	var schema string
	require.NoError(t, db.Raw(`SELECT current_schema()`).Scan(&schema).Error)

	var out strings.Builder
	out.WriteString("-- Generated by TestMigrationsProduceGoldenSchema. Do not edit by hand.\n")

	type column struct {
		TableName  string
		ColumnName string
		DataType   string
		NotNull    bool
		DefaultSQL *string
	}
	var columns []column
	require.NoError(t, db.Raw(`
		SELECT c.relname AS table_name,
		       a.attname AS column_name,
		       format_type(a.atttypid, a.atttypmod) AS data_type,
		       a.attnotnull AS not_null,
		       pg_get_expr(d.adbin, d.adrelid) AS default_sql
		FROM pg_attribute a
		JOIN pg_class c ON c.oid = a.attrelid
		LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
		WHERE c.relnamespace = current_schema()::regnamespace
		  AND c.relkind = 'r'
		  AND a.attnum > 0
		  AND NOT a.attisdropped
		ORDER BY c.relname, a.attnum
	`).Scan(&columns).Error)
	currentTable := ""
	for _, col := range columns {
		if col.TableName != currentTable {
			currentTable = col.TableName
			fmt.Fprintf(&out, "\nTABLE %s\n", col.TableName)
		}
		line := fmt.Sprintf("  COLUMN %s %s", col.ColumnName, col.DataType)
		if col.NotNull {
			line += " NOT NULL"
		}
		if col.DefaultSQL != nil {
			line += " DEFAULT " + *col.DefaultSQL
		}
		out.WriteString(line + "\n")
	}

	type constraint struct {
		TableName  string
		Name       string
		Definition string
	}
	var constraints []constraint
	require.NoError(t, db.Raw(`
		SELECT cl.relname AS table_name, co.conname AS name, pg_get_constraintdef(co.oid) AS definition
		FROM pg_constraint co
		JOIN pg_class cl ON cl.oid = co.conrelid
		WHERE co.connamespace = current_schema()::regnamespace
		  AND co.contype IN ('p', 'u', 'f', 'c', 'x')
		ORDER BY cl.relname, co.conname
	`).Scan(&constraints).Error)
	out.WriteString("\n")
	for _, c := range constraints {
		fmt.Fprintf(&out, "CONSTRAINT %s.%s %s\n", c.TableName, c.Name, c.Definition)
	}

	type index struct {
		IndexName  string
		Definition string
	}
	var indexes []index
	require.NoError(t, db.Raw(`
		SELECT indexname AS index_name, indexdef AS definition
		FROM pg_indexes
		WHERE schemaname = current_schema()
		ORDER BY tablename, indexname
	`).Scan(&indexes).Error)
	out.WriteString("\n")
	for _, idx := range indexes {
		definition := strings.ReplaceAll(idx.Definition, schema+".", "")
		definition = strings.ReplaceAll(definition, `"`+schema+`".`, "")
		fmt.Fprintf(&out, "INDEX %s\n", definition)
	}
	return out.String()
}
