-- Generated by TestMigrationsProduceGoldenSchema. Do not edit by hand.

TABLE api_keys
  COLUMN id bigint NOT NULL DEFAULT nextval('api_keys_id_seq'::regclass)
  COLUMN created_at timestamp with time zone
  COLUMN updated_at timestamp with time zone
  COLUMN deleted_at timestamp with time zone
  COLUMN user_id bigint NOT NULL
  COLUMN name character varying(100) NOT NULL
  COLUMN key_prefix character varying(32) NOT NULL
  COLUMN key_hash character varying(64) NOT NULL
  COLUMN scopes text
  COLUMN last_used_at timestamp with time zone
  COLUMN expires_at timestamp with time zone
  COLUMN revoked_at timestamp with time zone

TABLE assets
  COLUMN id character varying(36) NOT NULL
  COLUMN user_id bigint NOT NULL
  COLUMN idempotency_key character varying(128) NOT NULL
  COLUMN request_hash character varying(64) NOT NULL
  COLUMN original_name character varying(255) NOT NULL
  COLUMN media_type character varying(100) NOT NULL
  COLUMN size_bytes bigint NOT NULL
  COLUMN status character varying(24) NOT NULL
  COLUMN staging_key character varying(255) NOT NULL
  COLUMN object_key character varying(255) NOT NULL
  COLUMN checksum_sha256 character varying(64) NOT NULL DEFAULT ''::character varying
  COLUMN rejection_code character varying(64) NOT NULL DEFAULT ''::character varying
  COLUMN pending_expires_at timestamp with time zone NOT NULL
  COLUMN ready_at timestamp with time zone
  COLUMN deleted_at timestamp with time zone
  COLUMN operation_kind character varying(24) NOT NULL DEFAULT ''::character varying
  COLUMN operation_token character varying(64) NOT NULL DEFAULT ''::character varying
  COLUMN operation_until timestamp with time zone
  COLUMN created_at timestamp with time zone NOT NULL
  COLUMN updated_at timestamp with time zone NOT NULL

TABLE audit_logs
  COLUMN id bigint NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass)
  COLUMN created_at timestamp with time zone
  COLUMN updated_at timestamp with time zone
  COLUMN user_id bigint
  COLUMN actor_type character varying(20) NOT NULL
  COLUMN actor_id bigint
  COLUMN api_key_id bigint
  COLUMN action character varying(120) NOT NULL
  COLUMN resource character varying(180) NOT NULL
  COLUMN target_type character varying(80)
  COLUMN target_id character varying(120)
  COLUMN result character varying(40)
  COLUMN method character varying(10) NOT NULL
  COLUMN path character varying(255) NOT NULL
  COLUMN route_name character varying(180)
  COLUMN status_code bigint NOT NULL
  COLUMN request_id character varying(80)
  COLUMN ip_address character varying(64)
  COLUMN user_agent character varying(512)
  COLUMN changes text
  COLUMN metadata text

TABLE authentication_sessions
  COLUMN id character varying(32) NOT NULL
  COLUMN created_at timestamp with time zone
  COLUMN updated_at timestamp with time zone
  COLUMN user_id bigint NOT NULL
  COLUMN token_hash character varying(64) NOT NULL
  COLUMN expires_at timestamp with time zone NOT NULL
  COLUMN idle_expires_at timestamp with time zone NOT NULL
  COLUMN last_seen_at timestamp with time zone NOT NULL
  COLUMN revoked_at timestamp with time zone
  COLUMN revocation_reason character varying(32) NOT NULL DEFAULT ''::character varying

TABLE migrations
  COLUMN id integer NOT NULL DEFAULT nextval('migrations_id_seq'::regclass)
  COLUMN migration character varying(255) NOT NULL
  COLUMN batch integer NOT NULL

TABLE notification_deliveries
  COLUMN id bigint NOT NULL DEFAULT nextval('notification_deliveries_id_seq'::regclass)
  COLUMN notification_id bigint NOT NULL
  COLUMN channel character varying(24) NOT NULL
  COLUMN status character varying(24) NOT NULL
  COLUMN attempts smallint NOT NULL DEFAULT 0
  COLUMN available_at timestamp with time zone NOT NULL
  COLUMN lease_token character varying(64) NOT NULL DEFAULT ''::character varying
  COLUMN lease_expires_at timestamp with time zone
  COLUMN destination_hash character varying(64) NOT NULL DEFAULT ''::character varying
  COLUMN delivered_at timestamp with time zone
  COLUMN last_failure_code character varying(64) NOT NULL DEFAULT ''::character varying
  COLUMN created_at timestamp with time zone NOT NULL
  COLUMN updated_at timestamp with time zone NOT NULL

TABLE notification_preferences
  COLUMN user_id bigint NOT NULL DEFAULT nextval('notification_preferences_user_id_seq'::regclass)
  COLUMN in_app_enabled boolean NOT NULL
  COLUMN email_enabled boolean NOT NULL
  COLUMN created_at timestamp with time zone NOT NULL
  COLUMN updated_at timestamp with time zone NOT NULL

TABLE notifications
  COLUMN id bigint NOT NULL DEFAULT nextval('notifications_id_seq'::regclass)
  COLUMN user_id bigint NOT NULL
  COLUMN idempotency_key character varying(128) NOT NULL
  COLUMN publication_hash character varying(64) NOT NULL
  COLUMN kind character varying(100) NOT NULL
  COLUMN title character varying(640) NOT NULL
  COLUMN body text NOT NULL
  COLUMN action_url character varying(2048) NOT NULL DEFAULT ''::character varying
  COLUMN read_at timestamp with time zone
  COLUMN created_at timestamp with time zone NOT NULL
  COLUMN updated_at timestamp with time zone NOT NULL

TABLE organization_invitations
  COLUMN id bigint NOT NULL DEFAULT nextval('organization_invitations_id_seq'::regclass)
  COLUMN organization_id bigint NOT NULL
  COLUMN invited_by bigint NOT NULL
  COLUMN email character varying(100) NOT NULL
  COLUMN role character varying(16) NOT NULL
  COLUMN token_hash character varying(64) NOT NULL
  COLUMN pending_key character varying(64)
  COLUMN expires_at timestamp with time zone NOT NULL
  COLUMN accepted_at timestamp with time zone
  COLUMN accepted_by bigint
  COLUMN revoked_at timestamp with time zone
  COLUMN revoked_by bigint
  COLUMN created_at timestamp with time zone
  COLUMN updated_at timestamp with time zone

TABLE organization_memberships
  COLUMN id bigint NOT NULL DEFAULT nextval('organization_memberships_id_seq'::regclass)
  COLUMN organization_id bigint NOT NULL
  COLUMN user_id bigint NOT NULL
  COLUMN role character varying(16) NOT NULL
  COLUMN created_at timestamp with time zone
  COLUMN updated_at timestamp with time zone

TABLE organizations
  COLUMN id bigint NOT NULL DEFAULT nextval('organizations_id_seq'::regclass)
  COLUMN name character varying(100) NOT NULL
  COLUMN slug character varying(50) NOT NULL
  COLUMN created_by bigint NOT NULL
  COLUMN created_at timestamp with time zone
  COLUMN updated_at timestamp with time zone

TABLE password_reset_tokens
  COLUMN id bigint NOT NULL DEFAULT nextval('password_reset_tokens_id_seq'::regclass)
  COLUMN created_at timestamp with time zone
  COLUMN updated_at timestamp with time zone
  COLUMN user_id bigint NOT NULL
  COLUMN token_hash character varying(64) NOT NULL
  COLUMN expires_at timestamp with time zone NOT NULL
  COLUMN used_at timestamp with time zone

TABLE permission_role_assignments
  COLUMN id bigint NOT NULL DEFAULT nextval('permission_role_assignments_id_seq'::regclass)
  COLUMN organization_id bigint NOT NULL
  COLUMN membership_id bigint NOT NULL
  COLUMN access_role_id bigint NOT NULL
  COLUMN created_at timestamp with time zone

TABLE permission_role_grants
  COLUMN access_role_id bigint NOT NULL
  COLUMN permission character varying(100) NOT NULL
  COLUMN created_at timestamp with time zone

TABLE permission_roles
  COLUMN id bigint NOT NULL DEFAULT nextval('permission_roles_id_seq'::regclass)
  COLUMN organization_id bigint NOT NULL
  COLUMN name character varying(100) NOT NULL
  COLUMN slug character varying(50) NOT NULL
  COLUMN created_at timestamp with time zone
  COLUMN updated_at timestamp with time zone

TABLE platform_operators
  COLUMN user_id bigint NOT NULL
  COLUMN granted_at timestamp with time zone NOT NULL

TABLE settings
  COLUMN id bigint NOT NULL DEFAULT nextval('settings_id_seq'::regclass)
  COLUMN scope character varying(24) NOT NULL
  COLUMN subject_id bigint NOT NULL
  COLUMN user_id bigint
  COLUMN organization_id bigint
  COLUMN key character varying(96) NOT NULL
  COLUMN value_json text NOT NULL DEFAULT ''::text
  COLUMN is_overridden boolean NOT NULL DEFAULT false
  COLUMN version bigint NOT NULL
  COLUMN created_at timestamp with time zone
  COLUMN updated_at timestamp with time zone

TABLE usage_counters
  COLUMN id bigint NOT NULL DEFAULT nextval('usage_counters_id_seq'::regclass)
  COLUMN scope character varying(24) NOT NULL
  COLUMN subject_id bigint NOT NULL
  COLUMN user_id bigint
  COLUMN organization_id bigint
  COLUMN metric character varying(96) NOT NULL
  COLUMN period_start timestamp with time zone NOT NULL
  COLUMN period_end timestamp with time zone NOT NULL
  COLUMN value bigint NOT NULL
  COLUMN version bigint NOT NULL
  COLUMN created_at timestamp with time zone
  COLUMN updated_at timestamp with time zone

TABLE usage_events
  COLUMN id bigint NOT NULL DEFAULT nextval('usage_events_id_seq'::regclass)
  COLUMN source character varying(64) NOT NULL
  COLUMN event_id character varying(128) NOT NULL
  COLUMN fingerprint character varying(64) NOT NULL
  COLUMN operation character varying(16) NOT NULL
  COLUMN scope character varying(24) NOT NULL
  COLUMN subject_id bigint NOT NULL
  COLUMN user_id bigint
  COLUMN organization_id bigint
  COLUMN metric character varying(96) NOT NULL
  COLUMN quantity bigint NOT NULL
  COLUMN dimensions_json text NOT NULL DEFAULT '{}'::text
  COLUMN occurred_at timestamp with time zone NOT NULL
  COLUMN period_start timestamp with time zone NOT NULL
  COLUMN period_end timestamp with time zone NOT NULL
  COLUMN decision character varying(16) NOT NULL
  COLUMN counter_before bigint NOT NULL
  COLUMN counter_after bigint NOT NULL
  COLUMN limit_value bigint
  COLUMN created_at timestamp with time zone
  COLUMN updated_at timestamp with time zone

TABLE usage_quotas
  COLUMN id bigint NOT NULL DEFAULT nextval('usage_quotas_id_seq'::regclass)
  COLUMN scope character varying(24) NOT NULL
  COLUMN subject_id bigint NOT NULL
  COLUMN user_id bigint
  COLUMN organization_id bigint
  COLUMN metric character varying(96) NOT NULL
  COLUMN limit_value bigint
  COLUMN is_overridden boolean NOT NULL DEFAULT false
  COLUMN version bigint NOT NULL
  COLUMN created_at timestamp with time zone
  COLUMN updated_at timestamp with time zone

TABLE users
  COLUMN id bigint NOT NULL DEFAULT nextval('users_id_seq'::regclass)
  COLUMN created_at timestamp with time zone
  COLUMN updated_at timestamp with time zone
  COLUMN deleted_at timestamp with time zone
  COLUMN username character varying(50) NOT NULL
  COLUMN password character varying(100) NOT NULL
  COLUMN email character varying(100) NOT NULL
  COLUMN nickname character varying(50)
  COLUMN avatar character varying(255)
  COLUMN phone character varying(20)
  COLUMN bio character varying(500)
  COLUMN status bigint DEFAULT 1
  COLUMN last_login timestamp with time zone

TABLE webhook_deliveries
  COLUMN id bigint NOT NULL DEFAULT nextval('webhook_deliveries_id_seq'::regclass)
  COLUMN organization_id bigint NOT NULL
  COLUMN endpoint_id bigint NOT NULL
  COLUMN event_id bigint NOT NULL
  COLUMN destination_hash character varying(64) NOT NULL
  COLUMN status character varying(16) NOT NULL
  COLUMN attempt_count integer NOT NULL DEFAULT 0
  COLUMN cycle_attempt smallint NOT NULL DEFAULT 0
  COLUMN replay_count integer NOT NULL DEFAULT 0
  COLUMN available_at timestamp with time zone NOT NULL
  COLUMN lease_token character varying(64) NOT NULL DEFAULT ''::character varying
  COLUMN lease_expires_at timestamp with time zone
  COLUMN http_status bigint
  COLUMN failure_code character varying(64) NOT NULL DEFAULT ''::character varying
  COLUMN response_truncated boolean NOT NULL DEFAULT false
  COLUMN delivered_at timestamp with time zone
  COLUMN created_at timestamp with time zone
  COLUMN updated_at timestamp with time zone

TABLE webhook_delivery_attempts
  COLUMN id bigint NOT NULL DEFAULT nextval('webhook_delivery_attempts_id_seq'::regclass)
  COLUMN organization_id bigint NOT NULL
  COLUMN delivery_id bigint NOT NULL
  COLUMN number integer NOT NULL
  COLUMN outcome character varying(32) NOT NULL
  COLUMN http_status bigint
  COLUMN failure_code character varying(64) NOT NULL DEFAULT ''::character varying
  COLUMN duration_ms bigint NOT NULL
  COLUMN response_truncated boolean NOT NULL DEFAULT false
  COLUMN started_at timestamp with time zone NOT NULL
  COLUMN completed_at timestamp with time zone NOT NULL

TABLE webhook_endpoints
  COLUMN id bigint NOT NULL DEFAULT nextval('webhook_endpoints_id_seq'::regclass)
  COLUMN organization_id bigint NOT NULL
  COLUMN name character varying(100) NOT NULL
  COLUMN url character varying(2048) NOT NULL
  COLUMN url_hash character varying(64) NOT NULL
  COLUMN status character varying(16) NOT NULL
  COLUMN disabled_reason character varying(64) NOT NULL DEFAULT ''::character varying
  COLUMN consecutive_failures smallint NOT NULL DEFAULT 0
  COLUMN version bigint NOT NULL
  COLUMN secret_ciphertext text NOT NULL
  COLUMN secret_hint character varying(16) NOT NULL
  COLUMN secret_version bigint NOT NULL
  COLUMN previous_secret_ciphertext text NOT NULL DEFAULT ''::text
  COLUMN previous_secret_valid_until timestamp with time zone
  COLUMN created_by bigint NOT NULL
  COLUMN updated_by bigint NOT NULL
  COLUMN created_at timestamp with time zone
  COLUMN updated_at timestamp with time zone
  COLUMN deleted_at timestamp with time zone

TABLE webhook_events
  COLUMN id bigint NOT NULL DEFAULT nextval('webhook_events_id_seq'::regclass)
  COLUMN organization_id bigint NOT NULL
  COLUMN message_id character varying(64) NOT NULL
  COLUMN source character varying(64) NOT NULL
  COLUMN event_id character varying(128) NOT NULL
  COLUMN fingerprint character varying(64) NOT NULL
  COLUMN event_type character varying(100) NOT NULL
  COLUMN payload_json text NOT NULL
  COLUMN occurred_at timestamp with time zone NOT NULL
  COLUMN created_at timestamp with time zone

TABLE webhook_subscriptions
  COLUMN id bigint NOT NULL DEFAULT nextval('webhook_subscriptions_id_seq'::regclass)
  COLUMN endpoint_id bigint NOT NULL
  COLUMN organization_id bigint NOT NULL
  COLUMN event_type character varying(100) NOT NULL
  COLUMN created_at timestamp with time zone

TABLE workflow_tasks
  COLUMN id uuid NOT NULL
  COLUMN queue character varying(128) NOT NULL
  COLUMN idempotency_key character varying(128)
  COLUMN payload jsonb NOT NULL
  COLUMN payload_hash character varying(64) NOT NULL
  COLUMN status character varying(20) NOT NULL
  COLUMN attempts bigint NOT NULL DEFAULT 0
  COLUMN max_attempts bigint NOT NULL
  COLUMN available_at timestamp with time zone NOT NULL
  COLUMN lease_token character varying(64) NOT NULL DEFAULT ''::character varying
  COLUMN lease_expires_at timestamp with time zone
  COLUMN fencing_token bigint NOT NULL DEFAULT 0
  COLUMN cancel_requested_at timestamp with time zone
  COLUMN completed_at timestamp with time zone
  COLUMN failed_at timestamp with time zone
  COLUMN last_failure_code character varying(64) NOT NULL DEFAULT ''::character varying
  COLUMN created_at timestamp with time zone NOT NULL
  COLUMN updated_at timestamp with time zone NOT NULL

CONSTRAINT api_keys.api_keys_pkey PRIMARY KEY (id)
CONSTRAINT assets.assets_pkey PRIMARY KEY (id)
CONSTRAINT assets.assets_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'ready'::character varying, 'rejected'::character varying, 'deleted'::character varying])::text[])))
CONSTRAINT assets.fk_assets_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT
CONSTRAINT audit_logs.audit_logs_pkey PRIMARY KEY (id)
CONSTRAINT authentication_sessions.authentication_sessions_pkey PRIMARY KEY (id)
CONSTRAINT migrations.migrations_pkey PRIMARY KEY (id)
CONSTRAINT notification_deliveries.fk_notifications_deliveries FOREIGN KEY (notification_id) REFERENCES notifications(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT notification_deliveries.notification_deliveries_channel_check CHECK (((channel)::text = ANY ((ARRAY['in_app'::character varying, 'email'::character varying])::text[])))
CONSTRAINT notification_deliveries.notification_deliveries_pkey PRIMARY KEY (id)
CONSTRAINT notification_deliveries.notification_deliveries_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying, 'delivered'::character varying, 'failed'::character varying])::text[])))
CONSTRAINT notification_preferences.fk_notification_preferences_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT notification_preferences.notification_preferences_pkey PRIMARY KEY (user_id)
CONSTRAINT notifications.fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT notifications.notifications_pkey PRIMARY KEY (id)
CONSTRAINT organization_invitations.fk_organization_invitations_acceptor FOREIGN KEY (accepted_by) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT
CONSTRAINT organization_invitations.fk_organization_invitations_inviter FOREIGN KEY (invited_by) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT
CONSTRAINT organization_invitations.fk_organization_invitations_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT organization_invitations.fk_organization_invitations_revoker FOREIGN KEY (revoked_by) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT
CONSTRAINT organization_invitations.organization_invitations_pkey PRIMARY KEY (id)
CONSTRAINT organization_invitations.organization_invitations_role_check CHECK (((role)::text = ANY ((ARRAY['admin'::character varying, 'member'::character varying])::text[])))
CONSTRAINT organization_memberships.fk_organization_memberships_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT organization_memberships.fk_organization_memberships_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT
CONSTRAINT organization_memberships.organization_memberships_pkey PRIMARY KEY (id)
CONSTRAINT organization_memberships.organization_memberships_role_check CHECK (((role)::text = ANY ((ARRAY['owner'::character varying, 'admin'::character varying, 'member'::character varying])::text[])))
CONSTRAINT organizations.fk_organizations_creator FOREIGN KEY (created_by) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT
CONSTRAINT organizations.organizations_pkey PRIMARY KEY (id)
CONSTRAINT password_reset_tokens.password_reset_tokens_pkey PRIMARY KEY (id)
CONSTRAINT permission_role_assignments.fk_permission_role_assignments_access_role FOREIGN KEY (access_role_id) REFERENCES permission_roles(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT permission_role_assignments.fk_permission_role_assignments_membership FOREIGN KEY (membership_id) REFERENCES organization_memberships(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT permission_role_assignments.fk_permission_role_assignments_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT permission_role_assignments.permission_role_assignments_pkey PRIMARY KEY (id)
CONSTRAINT permission_role_grants.fk_permission_roles_permissions FOREIGN KEY (access_role_id) REFERENCES permission_roles(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT permission_role_grants.permission_role_grants_pkey PRIMARY KEY (access_role_id, permission)
CONSTRAINT permission_roles.fk_permission_roles_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT permission_roles.permission_roles_pkey PRIMARY KEY (id)
CONSTRAINT platform_operators.fk_platform_operators_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT platform_operators.platform_operators_pkey PRIMARY KEY (user_id)
CONSTRAINT settings.fk_settings_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT settings.fk_settings_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT settings.settings_key_check CHECK (((length((key)::text) >= 1) AND (length((key)::text) <= 96)))
CONSTRAINT settings.settings_pkey PRIMARY KEY (id)
CONSTRAINT settings.settings_scope_check CHECK (((scope)::text = ANY ((ARRAY['app'::character varying, 'organization'::character varying, 'user'::character varying])::text[])))
CONSTRAINT settings.settings_subject_check CHECK (((((scope)::text = 'app'::text) AND (subject_id = 0) AND (user_id IS NULL) AND (organization_id IS NULL)) OR (((scope)::text = 'user'::text) AND (subject_id = user_id) AND (user_id IS NOT NULL) AND (organization_id IS NULL)) OR (((scope)::text = 'organization'::text) AND (subject_id = organization_id) AND (organization_id IS NOT NULL) AND (user_id IS NULL))))
CONSTRAINT settings.settings_value_state_check CHECK (((length(value_json) <= 4096) AND (((is_overridden = true) AND (value_json <> ''::text)) OR ((is_overridden = false) AND (value_json = ''::text)))))
CONSTRAINT settings.settings_version_check CHECK ((version > 0))
CONSTRAINT usage_counters.fk_usage_counters_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT usage_counters.fk_usage_counters_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT usage_counters.usage_counters_period_check CHECK ((period_end > period_start))
CONSTRAINT usage_counters.usage_counters_pkey PRIMARY KEY (id)
CONSTRAINT usage_counters.usage_counters_scope_check CHECK (((scope)::text = ANY ((ARRAY['user'::character varying, 'organization'::character varying])::text[])))
CONSTRAINT usage_counters.usage_counters_subject_check CHECK (((((scope)::text = 'user'::text) AND (subject_id = user_id) AND (user_id IS NOT NULL) AND (organization_id IS NULL)) OR (((scope)::text = 'organization'::text) AND (subject_id = organization_id) AND (organization_id IS NOT NULL) AND (user_id IS NULL))))
CONSTRAINT usage_counters.usage_counters_value_check CHECK (((value >= 0) AND (value <= '9007199254740991'::bigint)))
CONSTRAINT usage_counters.usage_counters_version_check CHECK ((version > 0))
CONSTRAINT usage_events.fk_usage_events_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT usage_events.fk_usage_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT usage_events.usage_events_counter_after_check CHECK ((((counter_after >= 0) AND (counter_after <= '9007199254740991'::bigint)) AND (((decision)::text <> 'denied'::text) OR (counter_after = counter_before))))
CONSTRAINT usage_events.usage_events_counter_before_check CHECK (((counter_before >= 0) AND (counter_before <= '9007199254740991'::bigint)))
CONSTRAINT usage_events.usage_events_decision_check CHECK (((decision)::text = ANY ((ARRAY['pending'::character varying, 'accepted'::character varying, 'denied'::character varying])::text[])))
CONSTRAINT usage_events.usage_events_dimensions_check CHECK (((length(dimensions_json) >= 2) AND (length(dimensions_json) <= 4096)))
CONSTRAINT usage_events.usage_events_fingerprint_check CHECK ((length((fingerprint)::text) = 64))
CONSTRAINT usage_events.usage_events_limit_check CHECK (((limit_value IS NULL) OR ((limit_value >= 0) AND (limit_value <= '9007199254740991'::bigint))))
CONSTRAINT usage_events.usage_events_operation_check CHECK (((operation)::text = ANY ((ARRAY['record'::character varying, 'consume'::character varying])::text[])))
CONSTRAINT usage_events.usage_events_period_check CHECK ((period_end > period_start))
CONSTRAINT usage_events.usage_events_pkey PRIMARY KEY (id)
CONSTRAINT usage_events.usage_events_quantity_check CHECK (((quantity <> 0) AND ((quantity >= '-9007199254740991'::bigint) AND (quantity <= '9007199254740991'::bigint)) AND (((operation)::text = 'record'::text) OR (quantity > 0))))
CONSTRAINT usage_events.usage_events_scope_check CHECK (((scope)::text = ANY ((ARRAY['user'::character varying, 'organization'::character varying])::text[])))
CONSTRAINT usage_events.usage_events_subject_check CHECK (((((scope)::text = 'user'::text) AND (subject_id = user_id) AND (user_id IS NOT NULL) AND (organization_id IS NULL)) OR (((scope)::text = 'organization'::text) AND (subject_id = organization_id) AND (organization_id IS NOT NULL) AND (user_id IS NULL))))
CONSTRAINT usage_quotas.fk_usage_quotas_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT usage_quotas.fk_usage_quotas_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT usage_quotas.usage_quotas_limit_check CHECK (((limit_value IS NULL) OR ((limit_value >= 0) AND (limit_value <= '9007199254740991'::bigint))))
CONSTRAINT usage_quotas.usage_quotas_pkey PRIMARY KEY (id)
CONSTRAINT usage_quotas.usage_quotas_scope_check CHECK (((scope)::text = ANY ((ARRAY['user'::character varying, 'organization'::character varying])::text[])))
CONSTRAINT usage_quotas.usage_quotas_state_check CHECK ((((is_overridden = true) AND (limit_value IS NOT NULL)) OR ((is_overridden = false) AND (limit_value IS NULL))))
CONSTRAINT usage_quotas.usage_quotas_subject_check CHECK (((((scope)::text = 'user'::text) AND (subject_id = user_id) AND (user_id IS NOT NULL) AND (organization_id IS NULL)) OR (((scope)::text = 'organization'::text) AND (subject_id = organization_id) AND (organization_id IS NOT NULL) AND (user_id IS NULL))))
CONSTRAINT usage_quotas.usage_quotas_version_check CHECK ((version > 0))
CONSTRAINT users.uni_users_email UNIQUE (email)
CONSTRAINT users.users_pkey PRIMARY KEY (id)
CONSTRAINT webhook_deliveries.fk_webhook_deliveries_endpoint FOREIGN KEY (endpoint_id) REFERENCES webhook_endpoints(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT webhook_deliveries.fk_webhook_deliveries_event FOREIGN KEY (event_id) REFERENCES webhook_events(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT webhook_deliveries.webhook_deliveries_destination_hash_check CHECK ((length((destination_hash)::text) = 64))
CONSTRAINT webhook_deliveries.webhook_deliveries_pkey PRIMARY KEY (id)
CONSTRAINT webhook_deliveries.webhook_deliveries_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying, 'delivered'::character varying, 'failed'::character varying, 'canceled'::character varying])::text[])))
CONSTRAINT webhook_delivery_attempts.fk_webhook_delivery_attempts_delivery FOREIGN KEY (delivery_id) REFERENCES webhook_deliveries(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT webhook_delivery_attempts.webhook_delivery_attempts_pkey PRIMARY KEY (id)
CONSTRAINT webhook_endpoints.fk_webhook_endpoints_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT webhook_endpoints.webhook_endpoints_name_check CHECK (((length((name)::text) >= 1) AND (length((name)::text) <= 100)))
CONSTRAINT webhook_endpoints.webhook_endpoints_pkey PRIMARY KEY (id)
CONSTRAINT webhook_endpoints.webhook_endpoints_secret_version_check CHECK ((secret_version > 0))
CONSTRAINT webhook_endpoints.webhook_endpoints_status_check CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'disabled'::character varying])::text[])))
CONSTRAINT webhook_endpoints.webhook_endpoints_url_check CHECK (((length((url)::text) >= 1) AND (length((url)::text) <= 2048)))
CONSTRAINT webhook_endpoints.webhook_endpoints_url_hash_check CHECK ((length((url_hash)::text) = 64))
CONSTRAINT webhook_endpoints.webhook_endpoints_version_check CHECK ((version > 0))
CONSTRAINT webhook_events.fk_webhook_events_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT webhook_events.webhook_events_fingerprint_check CHECK ((length((fingerprint)::text) = 64))
CONSTRAINT webhook_events.webhook_events_payload_check CHECK (((length(payload_json) >= 2) AND (length(payload_json) <= 65536)))
CONSTRAINT webhook_events.webhook_events_pkey PRIMARY KEY (id)
CONSTRAINT webhook_subscriptions.fk_webhook_endpoints_subscriptions FOREIGN KEY (endpoint_id) REFERENCES webhook_endpoints(id) ON UPDATE CASCADE ON DELETE CASCADE
CONSTRAINT webhook_subscriptions.webhook_subscriptions_pkey PRIMARY KEY (id)
CONSTRAINT workflow_tasks.workflow_tasks_pkey PRIMARY KEY (id)
CONSTRAINT workflow_tasks.workflow_tasks_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying, 'canceled'::character varying])::text[])))

INDEX CREATE UNIQUE INDEX api_keys_pkey ON api_keys USING btree (id)
INDEX CREATE INDEX idx_api_keys_deleted_at ON api_keys USING btree (deleted_at)
INDEX CREATE UNIQUE INDEX idx_api_keys_key_hash ON api_keys USING btree (key_hash)
INDEX CREATE INDEX idx_api_keys_key_prefix ON api_keys USING btree (key_prefix)
INDEX CREATE INDEX idx_api_keys_user_id ON api_keys USING btree (user_id)
INDEX CREATE UNIQUE INDEX assets_pkey ON assets USING btree (id)
INDEX CREATE INDEX idx_assets_cleanup ON assets USING btree (status, pending_expires_at)
INDEX CREATE INDEX idx_assets_operation_until ON assets USING btree (operation_until)
INDEX CREATE INDEX idx_assets_user_deleted_created ON assets USING btree (user_id, deleted_at, created_at DESC)
INDEX CREATE UNIQUE INDEX idx_assets_user_idempotency ON assets USING btree (user_id, idempotency_key)
INDEX CREATE INDEX idx_assets_user_status_deleted_created ON assets USING btree (user_id, status, deleted_at, created_at DESC)
INDEX CREATE UNIQUE INDEX audit_logs_pkey ON audit_logs USING btree (id)
INDEX CREATE INDEX idx_audit_logs_action ON audit_logs USING btree (action)
INDEX CREATE INDEX idx_audit_logs_actor_id ON audit_logs USING btree (actor_id)
INDEX CREATE INDEX idx_audit_logs_actor_type ON audit_logs USING btree (actor_type)
INDEX CREATE INDEX idx_audit_logs_api_key_id ON audit_logs USING btree (api_key_id)
INDEX CREATE INDEX idx_audit_logs_created_id ON audit_logs USING btree (created_at, id)
INDEX CREATE INDEX idx_audit_logs_method ON audit_logs USING btree (method)
INDEX CREATE INDEX idx_audit_logs_request_id ON audit_logs USING btree (request_id)
INDEX CREATE INDEX idx_audit_logs_resource ON audit_logs USING btree (resource)
INDEX CREATE INDEX idx_audit_logs_result ON audit_logs USING btree (result)
INDEX CREATE INDEX idx_audit_logs_route_name ON audit_logs USING btree (route_name)
INDEX CREATE INDEX idx_audit_logs_status_code ON audit_logs USING btree (status_code)
INDEX CREATE INDEX idx_audit_logs_target_id ON audit_logs USING btree (target_id)
INDEX CREATE INDEX idx_audit_logs_target_type ON audit_logs USING btree (target_type)
INDEX CREATE INDEX idx_audit_logs_user_id ON audit_logs USING btree (user_id)
INDEX CREATE UNIQUE INDEX authentication_sessions_pkey ON authentication_sessions USING btree (id)
INDEX CREATE INDEX idx_authentication_sessions_expires_at ON authentication_sessions USING btree (expires_at)
INDEX CREATE INDEX idx_authentication_sessions_idle_expires_at ON authentication_sessions USING btree (idle_expires_at)
INDEX CREATE INDEX idx_authentication_sessions_revoked_at ON authentication_sessions USING btree (revoked_at)
INDEX CREATE UNIQUE INDEX idx_authentication_sessions_token_hash ON authentication_sessions USING btree (token_hash)
INDEX CREATE INDEX idx_authentication_sessions_user_id ON authentication_sessions USING btree (user_id)
INDEX CREATE UNIQUE INDEX migrations_pkey ON migrations USING btree (id)
INDEX CREATE INDEX idx_notification_deliveries_leased ON notification_deliveries USING btree (channel, status, lease_expires_at)
INDEX CREATE UNIQUE INDEX idx_notification_deliveries_notification_channel ON notification_deliveries USING btree (notification_id, channel)
INDEX CREATE INDEX idx_notification_deliveries_notification_id ON notification_deliveries USING btree (notification_id)
INDEX CREATE INDEX idx_notification_deliveries_pending ON notification_deliveries USING btree (channel, status, available_at)
INDEX CREATE UNIQUE INDEX notification_deliveries_pkey ON notification_deliveries USING btree (id)
INDEX CREATE UNIQUE INDEX notification_preferences_pkey ON notification_preferences USING btree (user_id)
INDEX CREATE INDEX idx_notifications_kind ON notifications USING btree (kind)
INDEX CREATE INDEX idx_notifications_user_created ON notifications USING btree (user_id, created_at DESC)
INDEX CREATE UNIQUE INDEX idx_notifications_user_idempotency ON notifications USING btree (user_id, idempotency_key)
INDEX CREATE INDEX idx_notifications_user_read ON notifications USING btree (user_id, read_at)
INDEX CREATE UNIQUE INDEX notifications_pkey ON notifications USING btree (id)
INDEX CREATE INDEX idx_organization_invitations_accepted_at ON organization_invitations USING btree (accepted_at)
INDEX CREATE INDEX idx_organization_invitations_accepted_by ON organization_invitations USING btree (accepted_by)
INDEX CREATE INDEX idx_organization_invitations_expires_at ON organization_invitations USING btree (expires_at)
INDEX CREATE INDEX idx_organization_invitations_invited_by ON organization_invitations USING btree (invited_by)
INDEX CREATE INDEX idx_organization_invitations_org_created ON organization_invitations USING btree (organization_id, created_at)
INDEX CREATE INDEX idx_organization_invitations_org_email ON organization_invitations USING btree (organization_id, email)
INDEX CREATE UNIQUE INDEX idx_organization_invitations_pending_key ON organization_invitations USING btree (pending_key)
INDEX CREATE INDEX idx_organization_invitations_revoked_at ON organization_invitations USING btree (revoked_at)
INDEX CREATE INDEX idx_organization_invitations_revoked_by ON organization_invitations USING btree (revoked_by)
INDEX CREATE UNIQUE INDEX idx_organization_invitations_token_hash ON organization_invitations USING btree (token_hash)
INDEX CREATE UNIQUE INDEX organization_invitations_pkey ON organization_invitations USING btree (id)
INDEX CREATE UNIQUE INDEX idx_organization_memberships_org_user ON organization_memberships USING btree (organization_id, user_id)
INDEX CREATE INDEX idx_organization_memberships_user_created ON organization_memberships USING btree (user_id, created_at)
INDEX CREATE INDEX idx_organization_memberships_user_role ON organization_memberships USING btree (user_id, role)
INDEX CREATE UNIQUE INDEX organization_memberships_pkey ON organization_memberships USING btree (id)
INDEX CREATE INDEX idx_organizations_created_by ON organizations USING btree (created_by)
INDEX CREATE UNIQUE INDEX idx_organizations_slug ON organizations USING btree (slug)
INDEX CREATE UNIQUE INDEX organizations_pkey ON organizations USING btree (id)
INDEX CREATE INDEX idx_password_reset_tokens_expires_at ON password_reset_tokens USING btree (expires_at)
INDEX CREATE UNIQUE INDEX idx_password_reset_tokens_token_hash ON password_reset_tokens USING btree (token_hash)
INDEX CREATE INDEX idx_password_reset_tokens_used_at ON password_reset_tokens USING btree (used_at)
INDEX CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens USING btree (user_id)
INDEX CREATE UNIQUE INDEX password_reset_tokens_pkey ON password_reset_tokens USING btree (id)
INDEX CREATE INDEX idx_permission_role_assignments_access_role_id ON permission_role_assignments USING btree (access_role_id)
INDEX CREATE INDEX idx_permission_role_assignments_org_member ON permission_role_assignments USING btree (organization_id, membership_id)
INDEX CREATE UNIQUE INDEX idx_permission_role_assignments_org_member_role ON permission_role_assignments USING btree (organization_id, membership_id, access_role_id)
INDEX CREATE UNIQUE INDEX permission_role_assignments_pkey ON permission_role_assignments USING btree (id)
INDEX CREATE INDEX idx_permission_role_grants_permission_role ON permission_role_grants USING btree (permission, access_role_id)
INDEX CREATE UNIQUE INDEX permission_role_grants_pkey ON permission_role_grants USING btree (access_role_id, permission)
INDEX CREATE UNIQUE INDEX idx_permission_roles_org_slug ON permission_roles USING btree (organization_id, slug)
INDEX CREATE INDEX idx_permission_roles_organization_id ON permission_roles USING btree (organization_id)
INDEX CREATE UNIQUE INDEX permission_roles_pkey ON permission_roles USING btree (id)
INDEX CREATE UNIQUE INDEX platform_operators_pkey ON platform_operators USING btree (user_id)
INDEX CREATE INDEX idx_settings_organization ON settings USING btree (organization_id, subject_id)
INDEX CREATE UNIQUE INDEX idx_settings_scope_subject_key ON settings USING btree (scope, subject_id, key)
INDEX CREATE INDEX idx_settings_user ON settings USING btree (user_id, subject_id)
INDEX CREATE UNIQUE INDEX settings_pkey ON settings USING btree (id)
INDEX CREATE INDEX idx_usage_counters_current ON usage_counters USING btree (scope, subject_id, metric, period_end)
INDEX CREATE UNIQUE INDEX idx_usage_counters_identity ON usage_counters USING btree (scope, subject_id, metric, period_start)
INDEX CREATE INDEX idx_usage_counters_organization ON usage_counters USING btree (organization_id)
INDEX CREATE INDEX idx_usage_counters_user ON usage_counters USING btree (user_id)
INDEX CREATE UNIQUE INDEX usage_counters_pkey ON usage_counters USING btree (id)
INDEX CREATE INDEX idx_usage_events_organization ON usage_events USING btree (organization_id)
INDEX CREATE UNIQUE INDEX idx_usage_events_source_event ON usage_events USING btree (source, event_id)
INDEX CREATE INDEX idx_usage_events_subject ON usage_events USING btree (scope, subject_id, metric, period_start)
INDEX CREATE INDEX idx_usage_events_user ON usage_events USING btree (user_id)
INDEX CREATE UNIQUE INDEX usage_events_pkey ON usage_events USING btree (id)
INDEX CREATE UNIQUE INDEX idx_usage_quotas_identity ON usage_quotas USING btree (scope, subject_id, metric)
INDEX CREATE INDEX idx_usage_quotas_organization ON usage_quotas USING btree (organization_id)
INDEX CREATE INDEX idx_usage_quotas_user ON usage_quotas USING btree (user_id)
INDEX CREATE UNIQUE INDEX usage_quotas_pkey ON usage_quotas USING btree (id)
INDEX CREATE INDEX idx_users_deleted_at ON users USING btree (deleted_at)
INDEX CREATE UNIQUE INDEX idx_users_username ON users USING btree (username)
INDEX CREATE UNIQUE INDEX uni_users_email ON users USING btree (email)
INDEX CREATE UNIQUE INDEX users_pkey ON users USING btree (id)
INDEX CREATE INDEX idx_webhook_deliveries_due ON webhook_deliveries USING btree (status, available_at, id)
INDEX CREATE INDEX idx_webhook_deliveries_endpoint ON webhook_deliveries USING btree (endpoint_id)
INDEX CREATE UNIQUE INDEX idx_webhook_deliveries_event_endpoint ON webhook_deliveries USING btree (event_id, endpoint_id)
INDEX CREATE INDEX idx_webhook_deliveries_lease_expiry ON webhook_deliveries USING btree (status, lease_expires_at)
INDEX CREATE INDEX idx_webhook_deliveries_organization_created ON webhook_deliveries USING btree (organization_id, created_at, id)
INDEX CREATE INDEX idx_webhook_deliveries_organization_endpoint_created ON webhook_deliveries USING btree (organization_id, endpoint_id, created_at, id)
INDEX CREATE INDEX idx_webhook_deliveries_organization_status_created ON webhook_deliveries USING btree (organization_id, status, created_at, id)
INDEX CREATE UNIQUE INDEX webhook_deliveries_pkey ON webhook_deliveries USING btree (id)
INDEX CREATE UNIQUE INDEX idx_webhook_attempts_delivery_number ON webhook_delivery_attempts USING btree (delivery_id, number)
INDEX CREATE INDEX idx_webhook_delivery_attempts_organization_id ON webhook_delivery_attempts USING btree (organization_id)
INDEX CREATE UNIQUE INDEX webhook_delivery_attempts_pkey ON webhook_delivery_attempts USING btree (id)
INDEX CREATE INDEX idx_webhook_endpoints_deleted_at ON webhook_endpoints USING btree (deleted_at)
INDEX CREATE INDEX idx_webhook_endpoints_organization_created ON webhook_endpoints USING btree (organization_id, created_at, id)
INDEX CREATE INDEX idx_webhook_endpoints_organization_status ON webhook_endpoints USING btree (organization_id, status, id)
INDEX CREATE INDEX idx_webhook_endpoints_previous_secret_expiry ON webhook_endpoints USING btree (previous_secret_valid_until)
INDEX CREATE UNIQUE INDEX webhook_endpoints_pkey ON webhook_endpoints USING btree (id)
INDEX CREATE INDEX idx_webhook_events_created ON webhook_events USING btree (created_at, id)
INDEX CREATE INDEX idx_webhook_events_event_type ON webhook_events USING btree (event_type)
INDEX CREATE UNIQUE INDEX idx_webhook_events_identity ON webhook_events USING btree (organization_id, source, event_id)
INDEX CREATE UNIQUE INDEX idx_webhook_events_message_id ON webhook_events USING btree (message_id)
INDEX CREATE INDEX idx_webhook_events_organization_created ON webhook_events USING btree (organization_id, created_at)
INDEX CREATE UNIQUE INDEX webhook_events_pkey ON webhook_events USING btree (id)
INDEX CREATE UNIQUE INDEX idx_webhook_subscriptions_endpoint_type ON webhook_subscriptions USING btree (endpoint_id, event_type)
INDEX CREATE INDEX idx_webhook_subscriptions_organization_type ON webhook_subscriptions USING btree (organization_id, event_type)
INDEX CREATE UNIQUE INDEX webhook_subscriptions_pkey ON webhook_subscriptions USING btree (id)
INDEX CREATE INDEX idx_workflow_tasks_claim ON workflow_tasks USING btree (queue, status, available_at)
INDEX CREATE INDEX idx_workflow_tasks_lease ON workflow_tasks USING btree (status, lease_expires_at)
INDEX CREATE UNIQUE INDEX idx_workflow_tasks_queue_idempotency ON workflow_tasks USING btree (queue, idempotency_key) WHERE (idempotency_key IS NOT NULL)
INDEX CREATE UNIQUE INDEX workflow_tasks_pkey ON workflow_tasks USING btree (id)
