version: '3.8'

services:
  luas-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luas-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=/api
      - NEXT_PUBLIC_DEPLOY_API_URL=http://localhost:8025/v1
      - NEXT_PUBLIC_PLATFORM_API_URL=http://localhost:8025/v1
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
